apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "expense-tracker-frontend.fullname" . }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "expense-tracker-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "expense-tracker-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "expense-tracker-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "expense-tracker-frontend.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
