nameOverride: "expensetracker-frontend"
fullnameOverride: ""

namespace: dev

replicaCount: 1

image:
  repository: somanathmuduli03/expensetracker-frontend
  tag: "1.1"
  pullPolicy: Always

imagePullSecrets:
  - name: dockerhub-secret

containerPort: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: app.afet.online
  tlsSecretName: app-afet-tls
